--Printer functions for testProfile
--Created on 06/14/24
 
--Firmware: 0 = Marlin; 1 = RRF; 2 = Klipper;
firmware = 2

 

--//////////////////////////////////////////////////Util functions - mainly for unit conversions
function round(number, decimals)
  --[[
    returns a rounded value of "number"
    ]]
  local power = 10^decimals
  return math.floor(number * power) / power
end
-----------------------
function vol_to_mass(volume, density)
  --[[
    converts current volume to mass.
    Used along with the next function to approximate filament consumption."
    ]]
  return density * volume
end
-----------------------
function e_to_mm_cube(filament_diameter, e)
  --[[
    Uses the filament's dimensions and extrusion width to approximate the volume (mm^3)
    Used along with the previous function to approximate filament consumption.
    ]]
  local r = filament_diameter / 2
  return (math.pi * r^2 ) * e
end
-----------------------
-- get the E value (for G1 move) from a specified deposition move
function e_from_dep(dep_length, dep_width, dep_height, extruder)
  --[[
    Yet to be understood
  ]]
  local r1 = dep_width / 2
  local r2 = filament_diameter_mm[extruder] / 2
  local extruded_vol = dep_length * math.pi * r1 * dep_height
  return extruded_vol / (math.pi * r2^2)
end
-----------------------
function jerk_to_junction_deviation(jerk, accel)
  --[[
    Converts Marlin jerk value to junction deviation
    ]]
  return 0.4 * ( (jerk^2) / accel )
end
-----------------------
-- marlin jerk * sqrt(2) = square corner velocity
-- scv = square corner velocity
function scv_to_jerk(scv) 
  --[[
    converts klipper scv value to marlin jerk value
    ]]
  return math.sqrt(2) * scv
end
-----------------------
function jerk_to_scv(jerk)
  --[[
    converts marlin jerk value to klipper scv value
    ]]
  return jerk/math.sqrt(2)
end


 
--//////////////////////////////////////////////////Defining main variables
extruder_e = 0
extruder_e_restart = 0
current_z = 0.0
changed_frate = false
processing = false
current_extruder = 0
current_frate = 0
current_fan_speed = -1
craftware_debug = true

path_type = {
--{ 'default',    'Craftware'}
  { ';perimeter',  ';segType:Perimeter' },
  { ';shell',      ';segType:HShell' },
  { ';infill',     ';segType:Infill' },
  { ';raft',       ';segType:Raft' },
  { ';brim',       ';segType:Skirt' },
  { ';shield',     ';segType:Pillar' },
  { ';support',    ';segType:Support' },
  { ';tower',      ';segType:Pillar'}
}

--//////////////////////////////////////////////////Main Functions - called by IceSL 
--################################################## HEADER & FOOTER 
function header()

    -- called to create the header of the G-Code file.

    output('G21 ; set units to millimeters')
    output('G90 ; use absolute coordinates')
    output('M82 ; extruder absolute mode') --constant
    
        
    --set limits
    output('; set velocity / acceleration limits')
    output('SET_VELOCITY_LIMIT VELOCITY=' .. (x_max_speed + y_max_speed)/2 .. ' ACCEL=' .. (x_max_acc + y_max_acc)/2 .. ' ACCEL_TO_DECEL=' .. ((x_max_acc + y_max_acc)/2)/2 .. ' SQUARE_CORNER_VELOCITY=' .. round(jerk_to_scv(default_jerk),2) )
        
    output('START_PRINT EXTRUDER_TEMP=' .. extruder_temp_degree_c[extruders[0]] .. ' BED_TEMP=' .. bed_temp_degree_c)
        
    --start auto bed leveling
    output('BED_MESH_CALIBRATE ; mesh bed leveling')
    output('G0 F' .. travel_speed_mm_per_sec * 60 .. 'X0 Y0 ; back to the origin to begin the purge')
        
    --purge extruder
    output('G0 F6000 X0.100 Y20.000 Z0.300')
    output('G92 E0')
    output('G1 F1500 Y220.000 E18.8   ; draw 1st line')
    output('G1 F5000 X0.400   ; move a little to the side')
    output('G1 F1000 Y20.000 E37.6  ; draw 2nd line')
    output('G92 E0')
    output('; done purging extruder')

    output('M109 T'.. current_extruder..' S' .. extruder_temp_degree_c[extruders[0]] .. ' ; wait for extruder temp')

    output('')
    --set Linear Advance k-factor
    output('SET_PRESSURE_ADVANCE ADVANCE=' .. filament_linear_adv_factor .. ' ; Linear/Pressure advance')


    -- additionnal informations for Klipper web API (Moonraker)
    -- if feedback from Moonraker is implemented in the choosen web UI (Mainsail, Fluidd, Octoprint), this info will be used for gcode previewing
    
    output('')
    output("; Additionnal informations for Mooraker API")
    output("; Generated by <" .. slicer_name .. " " .. slicer_version .. ">")
    output("; print_height_mm :\t" .. f(extent_z))
    output("; layer_count :'\t" .. f(extent_z/z_layer_height_mm))
    output("; filament_type : '\t" .. name_en)
    output("; filament_name : '\t" .. name_en)
    output("; filament_used_mm : '\t" .. f(filament_tot_length_mm[0]) )
    -- caution! density is in g/cm3, convertion to g/mm3 needed!
    output("; filament_used_g : '\t" .. f(vol_to_mass(e_to_mm_cube(filament_diameter_mm[0], filament_tot_length_mm[0]), filament_density/1000)) )
    output("; estimated_print_time_s : '\t" .. time_sec)
    output('')


    current_frate = travel_speed_mm_per_sec * 60
    changed_frate = true

end
        -----------------------
function footer()
  -- called to create the footer of the G-Code file.
output('END_PRINT')
  
    --set limits back to original values.
    output('; set velocity / acceleration limits')
    output('SET_VELOCITY_LIMIT VELOCITY=' .. (x_max_speed + y_max_speed)/2 .. ' ACCEL=' .. (x_max_acc + y_max_acc)/2 .. ' ACCEL_TO_DECEL=' .. ((x_max_acc + y_max_acc)/2)/2 .. ' SQUARE_CORNER_VELOCITY=' .. round(jerk_to_scv(default_jerk),2) )
  
ends
  

--################################################## COMMENT 
function comment(text)
  --[[
    called when outputting a comment "text".
    ]]
    output('; ' .. text)
end

-----------------------
--################################################## LAYER
function layer_start(zheight)
  --called at the start of a layer at height "zheight" (mm).
                                   
    output('; <layer ' .. layer_id .. '>')
    local frate = 100
    if layer_id == 0 then
      frate = 600
      if not layer_spiralized then
        output('G0 F' .. frate ..' Z' .. ff(zheight))
      end
    else
      if not layer_spiralized then
        output('G0 F' .. frate ..' Z' .. ff(zheight))
      end
    end
    current_frate = frate
    changed_frate = true
end
-----------------------
function layer_stop()
--called at the end of a layer.

  extruder_e_restart = extruder_e
  output('G92 E0')
  output('; </layer>')
                                  
end
                                  
-----------------------
--################################################## EXTRUDER
function extruder_start()
  --called before extruding.

end
-----------------------
function extruder_stop()
  --called after extruding.

end
-----------------------
function swap_extruder(ext1,ext2,x,y,z)
  --[[
    called when swapping extruder 'ext1' to 'ext2' at position x,y,z.
    ]]
  output('\n;swap_extruder')
    extruder_e_swap[ext1] = extruder_e_swap[ext1] + extruder_e[ext1] - extruder_e_reset[ext1]

    -- swap extruder
    output('G92 E0.0')
    output('T' .. ext2)
    output('G92 E0.0\n')

    current_extruder = ext2
    extruder_changed = true
    current_frate = travel_speed_mm_per_sec * 60
    changed_frate = true
end
-----------------------
--################################################## MOVEMENTS
function prime(extruder,e)
  --[[
    called when priming from value "e" with extruder "extruder". 
    This function must return the absolute value of the E-axis after priming.
    ]]
    output(';prime')
    local len   = filament_priming_mm[extruder]
    local speed = priming_mm_per_sec[extruder] * 60
    output('G1 F' .. speed .. ' E' .. ff(e + len - extruder_e_restart))
    extruder_e = e + len
    current_frate = speed
    changed_frate = true
    return e + len
end
-----------------------
function retract(extruder,e)
  --[[
    called when retracting from value "e" with extruder "extruder". 
    This function must return the absolute value of the-E axis after retracting.
    ]]
    output(';retract')
    local len   = filament_priming_mm[extruder]
    local speed = retract_mm_per_sec[extruder] * 60
    output('G1 F' .. speed .. ' E' .. ff(e - len - extruder_e_restart))
    extruder_e = e - len
    current_frate = speed
    changed_frate = true
    return e - len
  end
-----------------------
function move_e(e)
  --[[
    called when moving the E-axis to value "e" with the current extruder.
    ]]
    extruder_e = e
  
    local e_value =  extruder_e - extruder_e_restart
  
    if changed_frate == true then
      output('G1 F' .. current_frate .. ' E' .. ff(e_value))
      changed_frate = false
    else
      output('G1 E' .. ff(e_value))
    end
end
-----------------------
--################################################## PROGRESS 
function progress(percent)
  output('M73 P' .. percent)
end
-----------------------
--################################################## SET
function set_feedrate(rate)
  --[[
    called when setting the feed-rate of the printer to "rate".
    ]]
    if rate ~= current_frate then
      current_frate = rate
      changed_frate = true
    end
end
-----------------------
function set_fan_speed(speed)
  --[[
    called when setting the part cooling fan velocity to "speed" (%).
    ]]
    if speed ~= current_fan_speed then
      output('M106 S'.. math.floor(255 * speed/100))
      current_fan_speed = speed
    end
end
-----------------------
function set_extruder_temperature(extruder,temperature)
  --[[
    called when setting the extruder "extruder" temperature to "temperature".
    ]]
    output('M104 S' .. temperature)
end
-----------------------
--################################################## WAIT
function wait(sec,x,y,z)
  --[[
    called when the parameter "enable_min_layer_time" is set to true
    and the printing time for the layer is less than "min_layer_time_sec". 
    "sec" is the remaining time to achieve "min_layer_time_sec" and 
    "x,y,z" is where IceSL expects the head to be after the wait.
    ]]
    output("; WAIT --" .. sec .. "s remaining" )
    output("G0 F" .. travel_speed_mm_per_sec .. " X10 Y10")
    output("G4 S" .. sec .. "; wait for " .. sec .. "s")
    output("G0 F" .. travel_speed_mm_per_sec .. " X" .. f(x) .. " Y" .. f(y) .. " Z" .. ff(z))
  end
-----------------------
--################################################## MIXING PARAMETERS
function set_and_wait_extruder_temperature(extruder,temperature)
  --[[
    called when setting the extruder "extruder" temperature to "temperature" while waiting. 
    Used when printing with multiple extruders.
    ]]
    output('M109 S' .. temperature)
end
-----------------------
function set_mixing_ratios(ratios)
  --[[   
    called when setting the mixing ratios of each filament fed onto the mixing extruder; 
    "ratios" is a table containing the ratio for each filament (the add up to 1). 
    This function is only called when using color mixing.
    ]]
end        
-----------------------